In [3]:
import mymodule
mymodule.greeting("Ravi")
mymodule.sum(23,12)

Hello, Ravi
35


In [4]:
import mymodule as my # standard notation to access any module in python
my.greeting("Mohan")
my.sum(20,12)

Hello, Mohan
32


In [5]:
from mymodule import *
greeting("Alok")
sum(10,20)

Hello, Alok
30


In [6]:
from mymodule import *
greeting("Alok")
sum(10,20)

Hello, Alok
30


In [7]:
#NUMPY Array
import numpy as np
a=np.array([10,20,30])
print(a)

[10 20 30]


In [8]:
print(a.dtype)

int32


In [10]:
print(a.shape)

(3,)


In [11]:
print(a.size)

3


In [13]:
b=np.array([[1,2],[3,4],[5,6]])
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
print(b.shape)

(3, 2)


In [15]:
print(b.size)

6


In [16]:
b=b.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


In [21]:
#Slicing
b=np.array([[10,20],[30,40],[50,60]])
print(b)
print(b[2,0])

[[10 20]
 [30 40]
 [50 60]]
50


In [23]:
#min,max,sum
b=np.array([[10,20],[30,40],[50,60]])
print(b.max())
print(b.min())
print(b.sum())

60
10
210


In [27]:
#min,max,sum axis
b=np.array([[10,20],[30,40],[50,60]])
print(b)
print(b.max())
print(b.max(axis=0))
print(b.max(axis=1))


[[10 20]
 [30 40]
 [50 60]]
60
[50 60]
[20 40 60]


In [28]:
print(np.std(b))

17.07825127659933


In [29]:
a=np.array([[1,2,30],[10,15,4]])
b=np.array([[10,20,30],[40,50,60]])
print(a+b)

[[11 22 60]
 [50 65 64]]


In [31]:
arr=np.empty((3,2),dtype=int)
print(arr)

[[ 1  2]
 [30 10]
 [15  4]]


In [32]:
arr=np.zeros((3,2),dtype=int)
print(arr)

[[0 0]
 [0 0]
 [0 0]]


In [35]:
arr=np.ones((4,3),dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [36]:
#converting tuple into array
i=(1,2,3,4,5,6,7)
a=np.asarray(i)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


In [37]:
thisdict={"name":"Ravi", "City":"Lucknow","College":"BBD"}
a=np.asarray(thisdict)
print(type(a))
print(a)

<class 'numpy.ndarray'>
{'name': 'Ravi', 'City': 'Lucknow', 'College': 'BBD'}


In [40]:
#arange(start,stop,step)
a=np.arange(2,10,3)
print(a)

[2 5 8]


In [44]:
a=np.array([[1,2,30],[10,15,4],[50,40,90]])
print(a)
sum=0
for x in np.nditer(a):
    print(x)
    sum=sum+x
    
print(sum)

[[ 1  2 30]
 [10 15  4]
 [50 40 90]]
1
2
30
10
15
4
50
40
90
242


In [48]:
# Readind data column wise using order as F
a=np.array([[1,2,30],[10,15,4],[50,40,90]])
print(a)
for x in np.nditer(a,order='F'):
    print(x)

[[ 1  2 30]
 [10 15  4]
 [50 40 90]]
1
2
30
10
15
4
50
40
90


In [49]:
a=np.array([[1.234,2.678,30.456],[10.321,15.45,4],[50,40,90]])
print(np.around(a,2))

[[ 1.23  2.68 30.46]
 [10.32 15.45  4.  ]
 [50.   40.   90.  ]]


In [50]:
#Sorting Row wise
a=np.array([[1,2,30],[10,15,4],[50,40,90]])
print(np.sort(a))

[[ 1  2 30]
 [ 4 10 15]
 [40 50 90]]


In [52]:
#Sorting Column Wise
a=np.array([[1,2,30],[10,15,4],[50,40,90]])
print(a)
print(np.sort(a,0))

[[ 1  2 30]
 [10 15  4]
 [50 40 90]]
[[ 1  2  4]
 [10 15 30]
 [50 40 90]]


In [53]:
ap = np.array([2,45,20])  
ar=ap
ar[1]=900
print(ap)	# will display 2, 900,20



[  2 900  20]
